/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Libary.XFile;
import Model.Bill;
import Model.Menu;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class Management extends javax.swing.JFrame {
    
    DefaultTableModel tbMenuModel;
    String filePathMenu = "";
    ArrayList<Menu> menuList;
    
    DefaultTableModel tbBillModel;
    String filePathBill = "";
    ArrayList<Bill> billList;
    int currentMenuRow = -1;
    int currentBillRow = -1;
    
    /**
     * Creates new form Manage
     */
    public Management() {
        initComponents();
        this.setLocationRelativeTo(null);
        initTable();
        
        filePathMenu = "./src/Libary/menu.dat";
        menuList = new ArrayList<>();
        boolean menuFile = loadMenuFile();
        if(menuFile){
            fillToTableMenu();
        }
        
        filePathBill = "./src/Libary/bill.dat";
        billList = new ArrayList<>();
        boolean billFile = loadBillFile();
        if(billFile){
            fillToTableBill();
        }
        
        tbMenu.setDefaultEditor(Object.class, null);
        tbBill.setDefaultEditor(Object.class, null);
        
        txtItemTotal.setText(tbMenuModel.getRowCount()+"");
        txtItemTotal.setEditable(false);
        txtName.setEditable(false);
        txtCode.setEditable(false);
        txtPrice.setEditable(false);
        
        if(tbMenu.getRowCount()<1){
            btnSortByPrice.setEnabled(false);
        }
        
        if(currentMenuRow == -1){
            btnUpdateMenu.setEnabled(false);
            btnDeleteMenu.setEnabled(false);
        }
        
        if(currentBillRow == -1){
            btnUpdateBill.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        btnAddBill = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBill = new javax.swing.JTable();
        txtName = new javax.swing.JTextField();
        btnUpdateBill = new javax.swing.JButton();
        btnRefreshBill = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtItemPrice = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        btnAddMenu = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        btnUpdateMenu = new javax.swing.JButton();
        btnDeleteMenu = new javax.swing.JButton();
        lbLogout = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMenu = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        txtItemTotal = new javax.swing.JTextField();
        lbExit = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnRefreshMenu = new javax.swing.JButton();
        btnSortByPrice = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Bill");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText(" Manage Bills");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Price:");

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Quantity:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Code:");

        txtCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuantityFocusGained(evt);
            }
        });

        btnAddBill.setBackground(new java.awt.Color(102, 255, 102));
        btnAddBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddBill.setText("Add to bill");
        btnAddBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBillActionPerformed(evt);
            }
        });

        tbBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbBillMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbBill);

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnUpdateBill.setBackground(new java.awt.Color(255, 255, 102));
        btnUpdateBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateBill.setText("Update");
        btnUpdateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBillActionPerformed(evt);
            }
        });

        btnRefreshBill.setBackground(new java.awt.Color(102, 255, 255));
        btnRefreshBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefreshBill.setText("Refresh data");
        btnRefreshBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCode, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(txtQuantity))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAddBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdateBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefreshBill, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBill)
                    .addComponent(btnUpdateBill)
                    .addComponent(btnRefreshBill))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Price:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Name:");

        txtItemPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtItemPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemPriceFocusGained(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("Code:");

        txtItemCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtItemCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemCodeFocusGained(evt);
            }
        });

        btnAddMenu.setBackground(new java.awt.Color(102, 255, 102));
        btnAddMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddMenu.setText("Add to menu");
        btnAddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMenuActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel30.setText("Menu");
        jLabel30.setToolTipText("");

        txtItemName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtItemName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemNameFocusGained(evt);
            }
        });
        txtItemName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtItemNameInputMethodTextChanged(evt);
            }
        });

        btnUpdateMenu.setBackground(new java.awt.Color(255, 255, 102));
        btnUpdateMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateMenu.setText("Update");
        btnUpdateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMenuActionPerformed(evt);
            }
        });

        btnDeleteMenu.setBackground(new java.awt.Color(255, 102, 102));
        btnDeleteMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteMenu.setText("Delete from menu");
        btnDeleteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMenuActionPerformed(evt);
            }
        });

        lbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_logout_30px_2.png"))); // NOI18N
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbLogoutMousePressed(evt);
            }
        });

        tbMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbMenuMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbMenu);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setText("Total:");

        txtItemTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_close_window_30px.png"))); // NOI18N
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbExitMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText(" Manage Menu's Item");

        btnRefreshMenu.setBackground(new java.awt.Color(102, 255, 255));
        btnRefreshMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefreshMenu.setText("Refresh data");
        btnRefreshMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshMenuActionPerformed(evt);
            }
        });

        btnSortByPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSortByPrice.setText("Sort items by price");
        btnSortByPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddMenu)
                        .addGap(12, 12, 12)
                        .addComponent(btnUpdateMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtItemTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSortByPrice)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtItemPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefreshMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel29)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(101, 101, 101)
                .addComponent(lbLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbExit))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogout)
                    .addComponent(lbExit)
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtItemTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSortByPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshMenu)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMenu)
                    .addComponent(btnUpdateMenu)
                    .addComponent(btnDeleteMenu))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TheJavaCup.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 26)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("A Hot Cup of Happiness");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel10.setText("The Java Cup will be a place");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel11.setText("where people come together, ");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel14.setText("upholding the value of human");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel15.setText("connection and sharing ");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel16.setText("intimately with coffee and tea");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel17.setText("cups, inspiring modern life.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMenu(){
        filePathMenu = "./src/Libary/menu.dat";
        menuList = new ArrayList<>();
        boolean file = loadMenuFile();
        if(file){
            fillToTableMenu();
        }else{
            showMess("Creating menu file.");
        }
        
        String code = txtItemCode.getText().trim();
        String name = txtItemName.getText().trim();
        Integer price = Integer.valueOf(txtItemPrice.getText());
       
        Menu m = new Menu(code, name, price);
        menuList.add(m);
    }
    
    private void addBill(){
        filePathMenu = "./src/Libary/bill.dat";
        billList = new ArrayList<>();
        boolean file = loadBillFile();
        if(file){
            fillToTableBill();
        }else{
            showMess("Creating menu file.");
        }
        
        String code = txtCode.getText();
        String name = txtName.getText();
        Integer quantity = Integer.valueOf(txtQuantity.getText().trim());
        Integer price = Integer.valueOf(txtPrice.getText());
        Date date = new Date();
        
        Bill b = new Bill(code, name, price, quantity, price*quantity, date);
        billList.add(b);
    }
    
    public void updateMenu(){
        if (!txtItemName.getText().equals("") && !txtItemPrice.getText().equals("")) {
            for (int i = 0; i < txtItemPrice.getText().length(); i++) {
                boolean flags = Character.isDigit(txtItemPrice.getText().charAt(i));
                if(!flags){
                    txtItemPrice.setBackground(Color.red);
                    JOptionPane.showMessageDialog(this, "Price must be greater than 0 with numeric digits from 0-9.", "Wrong format", JOptionPane.ERROR_MESSAGE);
                    return;
                }else if(txtItemPrice.getText().equals(0+"")){
                    txtItemPrice.setBackground(Color.red);
                    return;
                }   
            }
            Menu m = menuList.get(currentMenuRow);
            m.setName(txtItemName.getText().trim());
            m.setPrice(Integer.valueOf(txtItemPrice.getText()));
        }else if(txtItemPrice.getText().equals("")){
            txtItemPrice.setBackground(Color.red);
        }else if(txtItemName.getText().equals("")){
            txtItemName.setBackground(Color.red);
        }
    }  
    
    private void deleteMenu(){
        if(currentMenuRow > -1){
            int result = JOptionPane.showConfirmDialog(this,
                    "Are you sure to delete this row?", "Warning", 
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                Menu m = menuList.get(currentMenuRow);
                menuList.remove(m);
                currentMenuRow = -1;
            }
        }
    }
    
    public void updateBill(){
        if (!txtName.getText().equals("") && !txtPrice.getText().equals("") && !txtCode.getText().equals("") && !txtQuantity.getText().equals("")) {
            for (int i = 0; i < txtQuantity.getText().length(); i++) {
                boolean flags = Character.isDigit(txtQuantity.getText().charAt(i));
                if(!flags){
                    txtQuantity.setBackground(Color.red);
                    JOptionPane.showMessageDialog(this, "Quantity must be greater than 0 with numeric digits from 0-9.", "Wrong format", JOptionPane.ERROR_MESSAGE);
                    return;
                }else if(txtQuantity.getText().equals(0+"")){
                    txtQuantity.setBackground(Color.red);
                    return;
               }
            }
            Bill b = billList.get(currentBillRow);
            b.setName(txtName.getText());
            b.setCode(txtCode.getText());
            b.setPrice(Integer.valueOf(txtPrice.getText()));
            b.setQuanity(Integer.valueOf(txtQuantity.getText()));
            b.setSubTotal(Integer.valueOf(txtPrice.getText())*Integer.valueOf(txtQuantity.getText()));
            resetBillForm();
        }else if(txtName.getText().equals("") && txtPrice.getText().equals("") && txtCode.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill out the information to update.");
        }else if(txtQuantity.getText().equals("")) {
            txtQuantity.setBackground(Color.red);
            txtQuantity.setOpaque(true);
        }
    }
    
    public void sortItemsByPrice(){
        Collections.sort(menuList, new Comparator<Menu>(){
            @Override
            public int compare(Menu o1, Menu o2) {
                return o1.getPrice()> o2.getPrice()?-1:1;
            }
        });
    }    
    
    private void fillToTableMenu(){
        tbMenuModel.setRowCount(0);
        for (Menu m : menuList){
            Object [] row = new Object[]{m.getCode(), m.getName(), m.getPrice()};
            tbMenuModel.addRow(row);
        }
    }
    
    private void fillToTableBill(){
        tbBillModel.setRowCount(0);
        for (Bill b : billList){
            Object [] row = new Object[]{b.getCode(), b.getName(), b.getPrice(), b.getQuanity(), b.getSubTotal(), b.getDate()};
            tbBillModel.addRow(row);
        }
    }
    
    private void saveMenuFile(){
        XFile.writeObject(filePathMenu, menuList);
    }
    
    private void saveBillFile(){
        XFile.writeObject(filePathBill, billList);
    }
    
    private boolean loadMenuFile(){
        if(XFile.readObject(filePathMenu) == null){
            return false;
        }
        menuList = (ArrayList<Menu>) XFile.readObject(filePathMenu);
        return true;
    }
    
    private boolean loadBillFile(){
        if( XFile.readObject(filePathBill) == null){
            return false;
        }
        billList = (ArrayList<Bill>) XFile.readObject(filePathBill);
        return true;
    }
    
    private void initTable(){
        String[] menuColumnNames = {"Code", "Name", "Price $"};
        tbMenuModel = new DefaultTableModel(menuColumnNames, 0);
        tbMenu.setModel(tbMenuModel);
        
        String[] billColumnNames = {"Code", "Name", "Price $", "Quantity", "Subtotal $", "Date"};
        tbBillModel = new DefaultTableModel(billColumnNames, 0);
        tbBill.setModel(tbBillModel);    
    }
    
    private void showMess(String mess) {
        JOptionPane.showMessageDialog(this, mess);
    }
    
    private void showMenuDetail(int r){
        String code = tbMenu.getValueAt(r, 0).toString();
        txtItemCode.setText(code);
        String name = tbMenu.getValueAt(r, 1).toString();
        txtItemName.setText(name);
        String price = tbMenu.getValueAt(r, 2).toString();
        txtItemPrice.setText(price);
    }
    
    private void addBillDetail(int r){
        String code = tbMenu.getValueAt(r, 0).toString();
        txtCode.setText(code);
        txtCode.setBackground(Color.white);
        String name = tbMenu.getValueAt(r, 1).toString();
        txtName.setText(name);
        txtName.setBackground(Color.white);
        String price = tbMenu.getValueAt(r, 2).toString();
        txtPrice.setText(price);
        txtPrice.setBackground(Color.white);
    }
    
    private void showBilDetail(int r){
        String code = tbBill.getValueAt(r, 0).toString();
        txtCode.setText(code);
        String name = tbBill.getValueAt(r, 1).toString();
        txtName.setText(name);
        String price = tbBill.getValueAt(r, 2).toString();
        txtPrice.setText(price);
        String quantity = tbBill.getValueAt(r, 3).toString();
        txtQuantity.setText(quantity);
    }
    
    private void btnAddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMenuActionPerformed
//        TODO add your handling code here:
        String name = txtItemName.getText();
        String code = txtItemCode.getText();
        String price = txtItemPrice.getText();
//        String regCode = "\\w\\d";
        
        if (!name.equals("") && !code.equals("") && !price.equals("")) {
            for (Menu mn : menuList) {
                Menu menu = new Menu(mn.getCode(), mn.getName(), mn.getPrice());
                if (code.equals(mn.getCode())) {
                    txtItemCode.setBackground(Color.red);
                    JOptionPane.showMessageDialog(this, "Code is existed.", "Failure", JOptionPane.ERROR_MESSAGE);
                    return;
//                }else if(!code.matches(regCode)){
//                    txtItemCode.setBackground(Color.red);
//                    JOptionPane.showMessageDialog(this, "Please enter code staring with a letter. Example: a001 or A001", "Wrong format", JOptionPane.ERROR_MESSAGE);
//                    return;
                }
            }
            for (int i = 0; i < price.length(); i++) {
                boolean flags = Character.isDigit(price.charAt(i));
                if(!flags){
                    txtItemPrice.setBackground(Color.red);
                    JOptionPane.showMessageDialog(this, "Price must be greater than 0 with numeric digits from 0-9.", "Wrong format", JOptionPane.ERROR_MESSAGE);
                    return;
                }else if(price.equals(0+"")){
                    txtItemPrice.setBackground(Color.red);
                    return;
               }
            }
            addMenu();
            fillToTableMenu();
            saveMenuFile();
            resetMenuForm();
        }else if(name.equals("") && code.equals("") && price.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter items information.", "Failure", JOptionPane.ERROR_MESSAGE);
        }else if(name.equals("")){
            txtItemName.setBackground(Color.red);
        }else if(code.equals("")){
            txtItemCode.setBackground(Color.red);
        }else if(price.equals("")){
            txtItemPrice.setBackground(Color.red);
        }
    }//GEN-LAST:event_btnAddMenuActionPerformed

    private void lbExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMousePressed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(
                this,
                "Do you want to exit?", "Warning?", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE
        );
        if(result == JOptionPane.YES_OPTION){
            System.exit(0);     
        }
    }//GEN-LAST:event_lbExitMousePressed

    private void lbLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMousePressed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(
                this,
                "Do you want to logout?", "Warning?", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE
        );
        if(result == JOptionPane.YES_OPTION){
            new Login().setVisible(true);
            this.setVisible(false);     
        }
    }//GEN-LAST:event_lbLogoutMousePressed

    private void tbMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMenuMousePressed
        // TODO add your handling code here:
        currentMenuRow = tbMenu.getSelectedRow();
        btnAddMenu.setEnabled(false);
        btnUpdateMenu.setEnabled(true);
        btnDeleteMenu.setEnabled(true);
        txtItemCode.setEditable(false);
        showMenuDetail(currentMenuRow);
        mouseClicked(evt);
    }//GEN-LAST:event_tbMenuMousePressed
    
    public void mouseClicked(MouseEvent evt) {
        if (evt.getClickCount() == 2) {
            addBillDetail(currentMenuRow);
        }
    }

    private void btnDeleteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMenuActionPerformed
        // TODO add your handling code here:
        deleteMenu();
        fillToTableMenu();
        saveMenuFile();
        resetMenuForm();
    }//GEN-LAST:event_btnDeleteMenuActionPerformed

    private void btnRefreshMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshMenuActionPerformed
        // TODO add your handling code here:
        resetMenuForm();
        btnAddMenu.setEnabled(true);
        btnUpdateMenu.setEnabled(false);
        btnDeleteMenu.setEnabled(false);
        txtItemCode.setEditable(true);
    }//GEN-LAST:event_btnRefreshMenuActionPerformed

    private void btnSortByPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByPriceActionPerformed
        // TODO add your handling code here:
        sortItemsByPrice();
        fillToTableMenu();
    }//GEN-LAST:event_btnSortByPriceActionPerformed

    private void txtItemNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtItemNameInputMethodTextChanged
        // TODO add your handling code here:
        txtItemName.setBackground(Color.white);
    }//GEN-LAST:event_txtItemNameInputMethodTextChanged

    private void btnUpdateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMenuActionPerformed
        // TODO add your handling code here:
        updateMenu();
        fillToTableMenu();
        saveMenuFile();
        resetMenuForm();
    }//GEN-LAST:event_btnUpdateMenuActionPerformed

    private void txtItemNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemNameFocusGained
        // TODO add your handling code here:
        txtItemName.setBackground(Color.white);
    }//GEN-LAST:event_txtItemNameFocusGained

    private void txtItemPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemPriceFocusGained
        // TODO add your handling code here:
        txtItemPrice.setBackground(Color.white);
    }//GEN-LAST:event_txtItemPriceFocusGained

    private void txtItemCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemCodeFocusGained
        // TODO add your handling code here:
        txtItemCode.setBackground(Color.white);
    }//GEN-LAST:event_txtItemCodeFocusGained

    private void btnAddBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBillActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText();
        String code = txtCode.getText();
        String price = txtPrice.getText();
        String quantity = txtQuantity.getText();
        if (!name.equals("") && !code.equals("") && !quantity.equals("")) {
            for (int i = 0; i < quantity.length(); i++) {
                boolean flags = Character.isDigit(quantity.charAt(i));
                if(!flags){
                    txtQuantity.setBackground(Color.red);
                    JOptionPane.showMessageDialog(this, "Quantity must be greater than 0 with numeric digits from 0-9.", "Wrong format", JOptionPane.ERROR_MESSAGE);
                    return;
                }else if(quantity.equals(0+"")){
                    txtQuantity.setBackground(Color.red);
                    return;
               }
            }
            addBill();
            fillToTableBill();
            saveBillFile();
            resetBillForm();
        }else if (name.equals("") && code.equals("") && price.equals("")){
            JOptionPane.showMessageDialog(this, "Please select an item.", "Failure", JOptionPane.ERROR_MESSAGE);
        }else if(quantity.equals("")){
            txtQuantity.setBackground(Color.red);
        }
    }//GEN-LAST:event_btnAddBillActionPerformed

    private void tbBillMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBillMousePressed
        // TODO add your handling code here:
        currentBillRow = tbBill.getSelectedRow();
        btnAddBill.setEnabled(false);
        btnUpdateBill.setEnabled(true);
        showBilDetail(currentBillRow);
    }//GEN-LAST:event_tbBillMousePressed

    private void txtQuantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusGained
        // TODO add your handling code here:
        txtQuantity.setBackground(Color.white);
    }//GEN-LAST:event_txtQuantityFocusGained

    private void btnUpdateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBillActionPerformed
        // TODO add your handling code here:
        updateBill();
        fillToTableBill();
        saveBillFile();
    }//GEN-LAST:event_btnUpdateBillActionPerformed

    private void btnRefreshBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshBillActionPerformed
        // TODO add your handling code here:
        resetBillForm();
    }//GEN-LAST:event_btnRefreshBillActionPerformed
    
    private void resetMenuForm(){
        txtItemCode.setText("");
        txtItemPrice.setText("");
        txtItemName.setText("");
        txtItemCode.setBackground(Color.white);
        txtItemName.setBackground(Color.white);
        txtItemPrice.setBackground(Color.white);
        txtItemTotal.setText(tbMenuModel.getRowCount()+"");
        txtItemCode.setEnabled(true);
        btnAddMenu.setEnabled(true);
        btnUpdateMenu.setEnabled(false);
        btnDeleteMenu.setEnabled(false);
    }
    
    private void resetBillForm(){
        txtCode.setText("");
        txtPrice.setText("");
        txtName.setText("");
        txtQuantity.setText("");
        txtCode.setBackground(Color.white);
        txtName.setBackground(Color.white);
        txtPrice.setBackground(Color.white);
        txtQuantity.setBackground(Color.white);
        btnAddBill.setEnabled(true);
        btnUpdateBill.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBill;
    private javax.swing.JButton btnAddMenu;
    private javax.swing.JButton btnDeleteMenu;
    private javax.swing.JButton btnRefreshBill;
    private javax.swing.JButton btnRefreshMenu;
    private javax.swing.JButton btnSortByPrice;
    private javax.swing.JButton btnUpdateBill;
    private javax.swing.JButton btnUpdateMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JTable tbBill;
    private javax.swing.JTable tbMenu;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemPrice;
    private javax.swing.JTextField txtItemTotal;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
